tem3/tem3/ViewComponents/SanVanDongViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using tem3.Models;

namespace ttem2.ViewComponents
{
    public class SanVanDongViewComponent : ViewComponent
    {
        QlgiaiBongDaContext db = new QlgiaiBongDaContext();

        public SanVanDongViewComponent()
        {

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

          var  sanvandongs = db.Sanvandongs.Take(7).ToList();

            return View("SanVanDong", sanvandongs);
        }

    }
}

tem3/tem3/Views/Shared/Footer.cshtml
<div class="footer">
	<div class="wrap">
		<div class="copy_right">
			<p>Copy rights (c). All rights Reseverd | Template by  <a href="http://w3layouts.com" target="_blank">W3Layouts</a> </p>
		</div>
		<div class="footer-nav">
			<ul>
				<li><a href="#">Terms of Use</a> : </li>
				<li><a href="#">Privacy Policy</a> : </li>
				<li><a href="contact.html">Contact Us</a> : </li>
				<li><a href="#">Sitemap</a></li>
			</ul>
		</div>
	</div>
</div>

tem3/tem3/Views/Shared/Header.cshtml
<div class="header">
	<div class="wrap">
		<div class="header_top">
			<div class="logo">
				<a href="index.html"><img src="images/logo.png" alt="" /></a>
			</div>
			<div class="header_top_right">
				<div class="search_box">
					<span>Search</span>
					<form>
						<input type="text" value=""><input type="submit" value="">
					</form>
					<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="navigation">
			<a class="toggleMenu" href="#">Menu</a>
			<ul class="nav">

				@await Component.InvokeAsync("SanVanDong")

			
			</ul>
			<span class="left-ribbon"> </span>
			<span class="right-ribbon"> </span>
		</div>
		<div class="header_bottom">
			<div class="slider-text">
				<h2>Lorem Ipsum Placerat <br />Elementum Quistue Tunulla Maris</h2>
				<p>Vivamus vitae augue at quam frigilla tristique sit amet<br /> acin ante sikumpre tisdin.</p>
				<a href="#">Sitamet Tortorions</a>
			</div>
			<div class="slider-img">
				<img src="images/slider-img.png" alt="" />
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>

tem3/tem3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tem3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tem3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tem3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - tem3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

tem3/tem3/Views/Shared/_LayoutChiTiet.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<head>
	<title>Free Ecomm Template Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
	<link href="../Tem/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="../Tem/js/jquery-1.9.0.min.js"></script>
	<script src="../Tem/js/jquery.openCarousel.js" type="text/javascript"></script>
	<script type="text/javascript" src="../Tem/js/easing.js"></script>
	<script type="text/javascript" src="../Tem/js/move-top.js"></script>

	<script src="../jjs/jquery-1.7.2.min.js"></script>
	<script src="../jjs/superfish.js"></script>
	<script src="../jjs/jquery.scrolltotop.js"></script>
	<link href="../assets/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
	<partial name="Header" />
	<!------------End Header ------------>
	<div class="main">
		<div id="renderbody" class="content">


			@RenderBody()



		</div>
	</div>
	<partial name="Footer" />


	<script type="text/javascript">
		$(document).ready(function() {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
	<a href="#" id="toTop"> </a>
	<script type="text/javascript" src="../Tem/js/navigation.js"></script>
</body>
</html>

tem3/tem3/Views/Shared/_LayoutKiemTra.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<head>
	<title>Free Ecomm Template Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
	<link href="../Tem/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="../Tem/js/jquery-1.9.0.min.js"></script>
	<script src="../Tem/js/jquery.openCarousel.js" type="text/javascript"></script>
	<script type="text/javascript" src="../Tem/js/easing.js"></script>
	<script type="text/javascript" src="../Tem/js/move-top.js"></script>

	<script src="../jjs/jquery-1.7.2.min.js"></script>
	<script src="../jjs/superfish.js"></script>
	<script src="../jjs/jquery.scrolltotop.js"></script>
	<link href="../assets/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
	<partial name="Header"/>
	<!------------End Header ------------>
	<div class="main">
		<div id="renderbody" class="content">
		

			@RenderBody()



		</div>
	</div>
	<partial name="Footer" />


	<script type="text/javascript">
		$(document).ready(function() {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
	<a href="#" id="toTop"> </a>
	<script type="text/javascript" src="../Tem/js/navigation.js"></script>
</body>
</html>